/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Interface;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Cliente;

/**
 *
 * @author Rafael
 */
public class CadClientes extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadClientes
     */
    public CadClientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("locadorafilme?zeroDateTimeBehavior=convertToNullPU").createEntityManager();
        clienteQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT c FROM Cliente c");
        clienteList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : clienteQuery.getResultList();
        jLabel2 = new javax.swing.JLabel();
        nomeCliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        codigoCliente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cpfCliente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        NascimentoCliente = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        dataCadastro = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        telefoneCliente = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        emailCliente = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        enderecoCliente = new javax.swing.JTextField();
        numeroCliente = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        bairroCliente = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        rgCliente = new javax.swing.JTextField();
        SalvarCliente = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setIconifiable(true);
        setTitle("Cadastro de Clientes");
        getContentPane().setLayout(null);

        jLabel2.setText("Nome:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 40, 70, 14);

        nomeCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeClienteActionPerformed(evt);
            }
        });
        getContentPane().add(nomeCliente);
        nomeCliente.setBounds(10, 60, 500, 30);

        jLabel3.setText("Codigo");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(540, 60, 50, 14);

        codigoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoClienteActionPerformed(evt);
            }
        });
        getContentPane().add(codigoCliente);
        codigoCliente.setBounds(590, 60, 18, 30);

        jLabel4.setText("CPF:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 100, 50, 14);
        getContentPane().add(cpfCliente);
        cpfCliente.setBounds(10, 120, 202, 30);

        jLabel5.setText("Data Nascimento");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(360, 100, 100, 14);
        getContentPane().add(NascimentoCliente);
        NascimentoCliente.setBounds(370, 120, 72, 30);

        jLabel6.setText("Data Cadastro");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(490, 100, 100, 14);

        dataCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataCadastroActionPerformed(evt);
            }
        });
        getContentPane().add(dataCadastro);
        dataCadastro.setBounds(490, 120, 148, 30);

        jLabel1.setText("Telefone");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 150, 70, 14);
        getContentPane().add(telefoneCliente);
        telefoneCliente.setBounds(10, 170, 194, 30);

        jLabel7.setText("E-mail:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(240, 150, 50, 14);
        getContentPane().add(emailCliente);
        emailCliente.setBounds(240, 170, 250, 30);

        jLabel8.setText("Endereço:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 210, 90, 14);
        getContentPane().add(enderecoCliente);
        enderecoCliente.setBounds(10, 230, 230, 30);
        getContentPane().add(numeroCliente);
        numeroCliente.setBounds(250, 230, 60, 30);

        jLabel9.setText("Bairro:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(340, 210, 70, 14);
        getContentPane().add(bairroCliente);
        bairroCliente.setBounds(340, 230, 190, 30);

        jLabel10.setText("Numero:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(250, 210, 60, 14);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nome", "CPF", "D. Nascimento", "D.Cadastro", "Telefone", "E-mail", "Endereço"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(0, 270, 670, 170);

        jLabel11.setText("RG:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(220, 100, 30, 20);
        getContentPane().add(rgCliente);
        rgCliente.setBounds(220, 120, 120, 30);

        SalvarCliente.setText("Salvar");
        SalvarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarClienteActionPerformed(evt);
            }
        });
        getContentPane().add(SalvarCliente);
        SalvarCliente.setBounds(30, 10, 63, 23);

        jButton2.setText("Excluir");
        getContentPane().add(jButton2);
        jButton2.setBounds(190, 10, 63, 23);

        jButton3.setText("Cancelar");
        getContentPane().add(jButton3);
        jButton3.setBounds(360, 10, 110, 23);

        setBounds(0, 0, 686, 474);
    }// </editor-fold>//GEN-END:initComponents

    private void dataCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataCadastroActionPerformed

    private void codigoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoClienteActionPerformed
     
    }//GEN-LAST:event_codigoClienteActionPerformed

    private void nomeClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeClienteActionPerformed

    private void SalvarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarClienteActionPerformed
       
               Cliente client = new Cliente();
               
                client.setCodigo(Integer.parseInt(codigoCliente.getText()));
                client.setNome(nomeCliente.getText());
                client.setCpf(Integer.parseInt(cpfCliente.getText()));
                client.setRg(Integer.parseInt(rgCliente.getText()));
                client.setDataNasc(NascimentoCliente.getText());
                client.setDataCadastro(dataCadastro.getText());
                client.setTelefone(telefoneCliente.getText());
                client.setEmail(emailCliente.getText());
                client.setEndereco(enderecoCliente.getText());
                client.setNumero(Integer.parseInt((numeroCliente.getText())));
                client.setBairro(bairroCliente.getText());     
                
                try {
            Registry conexao = LocateRegistry.getRegistry("127.0.0.1",1500);
            Interface objetoRemoto = (Interface) conexao.lookup("chave");
            JOptionPane.showMessageDialog(this,objetoRemoto.inserirCliente(client));
        } catch (RemoteException ex) {
            JOptionPane.showMessageDialog(null,"inserirido com sucesso");
        } catch (NotBoundException ex) {
            JOptionPane.showMessageDialog(null,"erro ao inserir");
        } 
        
        
        
        
    }//GEN-LAST:event_SalvarClienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NascimentoCliente;
    private javax.swing.JButton SalvarCliente;
    private javax.swing.JTextField bairroCliente;
    private java.util.List<view.Cliente> clienteList;
    private javax.persistence.Query clienteQuery;
    private javax.swing.JTextField codigoCliente;
    private javax.swing.JTextField cpfCliente;
    private javax.swing.JTextField dataCadastro;
    private javax.swing.JTextField emailCliente;
    private javax.swing.JTextField enderecoCliente;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField nomeCliente;
    private javax.swing.JTextField numeroCliente;
    private javax.swing.JTextField rgCliente;
    private javax.swing.JTextField telefoneCliente;
    // End of variables declaration//GEN-END:variables
}
